version: 2.1
orbs:
  notify-slack: interstellar/notify-slack@0.2.0

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: bash test.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build_and_test
